### ISSUE TITLE
Mypy doesn't catch wrong typing.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#103]
We have a function signature

```def handle_send_force_get_task_result(request, client_message: message.concents.ForceGetTaskResult) -> message.concents:```

which returns either `ForceGetTaskResultRejected` or `ForceGetTaskResultAck`. For some unknown reason, mypy is not complaining that returned type is not defined correctly. We should find out why.

The proper way of defining this signature according to mypy documentation should be

```def handle_send_force_get_task_result(request, client_message: message.concents.ForceGetTaskResult) -> Union[ForceGetTaskResultRejected, ForceGetTaskResultAck]:```

But for some reason, with that signature it doesn't complain if you put `return 11` somewhere in that function. So maybe the issue is not with signature itself.

It might be as well bug in mypy. I consider it not being mature library yet, but the most advanced from all currently available.

**Comment by kbeker** [comment]
I'm now reading docs from `mypy` and I'm thinking exactly which options do we want launch on? Or maybe what do we want to achieve by adding options to `mypy`? There is a lot of options and when I turned one of them on, console just got crazy from amount of warnings and errors from our code. 

And next thing is that during this task should I also fix all errors and warnings that will `mypy` show? 

Individually recommend a few settings to turn on:
`disallow_untyped_calls = True`
`disallow_untyped_defs = True`
`warn_no_return = True`
`warn_return_any = True`
`warn_unused_ignores = True`
`warn_redundant_casts = True`
`scripts_are_modules = True`

Just first two options returns **1056** errors and warnings. All of settings which are mentioned above gives in total **1076** warnings and errors.

Also I think that we should add to `full_check.sh` removing `.mypy_cache` because I saw that this makes  sometimes strange results of `mypy` work

All options I have found on [mypy docs page](http://mypy.readthedocs.io/en/latest/config_file.html)

**Comment by rwrzesien** [comment]
I would say we should discuss each one separately. For me those two look interesting and I would like to have them:
```
warn_unused_ignores = True
warn_redundant_casts = True
```

But I am against turning first two instantly, because we won't be able to tackle all those warnings for some time even if we put all our forces into it. Lets follow the current pattern in which we try to improve those places when we are doing some work around them or someone catches them during review.

Besides that, the more I work with Mypy the more I consider it to not be stable yet. We are finding a lot of bugs which are already reported, some of them a long time ago, but not fixed yet or any time soon. It looks to me like early usages of Pylint, when most of the time you wasn't sure if you are doing something wrong, or you have discovered a new bug. We also have very strict policy on disables, so I sometimes find myself ie. writing code for 30 minutes, and spend another 30 minutes to satisfy 2-3 Mypy warnings. I suggest we might loose up our disables policy on Mypy.

**Comment by dybi** [comment]
@kbeker, have you checked: http://mypy.readthedocs.io/en/latest/existing_code.html ?
It seems like a god way of introducing more`mypy` ;)

**Comment by kbeker** [comment]
@dybi I read some of these also and it's good idea to gradually add `mypy` warnings to some modules and fixing step by step all of them. Some day we could have nice and clean code :)
