### ISSUE TITLE
Replace raising SigningServiceMaximumReconnectionAttemptsExceeded in SigningService with logging

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#1075]
We have recurring `SigningServiceMaximumReconnectionAttemptsExceeded` exception being raised and reported to Sentry, which was good when we wanted to synchronize connection, but now it might happen for various reasons and we could replace it with logging.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163361953

**Comment by cameel** [comment]
Yeah. Detecting connection problems is the job of the monitoring system (meant for cluster admins), rather than error reporting system (meant for developers). This task is about freeing developers from this nagging report they can't really do anything about. Back when the setting for max reconnections in SS was being implemented I discussed the feature with @dybi. I'm not sure if we explicitly agreed about whether this should be reported or not (we probably did) but now I think it should not. Sentry because Sentry is being flooded by these messages while it's not something developers can fix or are responsible for. Having them there only desensitizes everyone to real problems.

Instead we need to redirect it to monitoring. Monitoring of Signing Service itself is up to Golem team but we can still notice the problem on Concent side. I think that Middleman should log an error after it has not seen SS for a significant period of time (e.g. 2 minutes; should be configurable of course). After that we should add filters to detect events like this and enable notifications for them on the clusters where it really matters (`testnet`, `mainnet`). These notifications should only go to the people managing these clusters (so me and @bartoszbetka for now).

@rwrzesien @dybi @bartoszbetka 
What do you think about it?

**Comment by rwrzesien** [comment]
@cameel Sounds good. Apart from that, if we wanted to move monitoring of `SigningService` exceptions out of our Sentry we might just set `sentry_dsn` to a different one.
