### ISSUE TITLE
Avoid failing when the Ethereum client gets out of sync for a very brief period of time

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#1077]
Concent should detect when there are small desynchronizations in SCI or if it is fully desynchronized and react properly:
1. If `SCI.is_synchronized` method returns False, raise custom exception, then handle it in decorator and return HTTP 502 response.
2. If `SCI.is_synchronized` method returns True ignore exceptions raised during method call like:
    - `ValueError` with message like `{'code': -32000, 'message': 'missing trie node 2c7d74c7796bf936ab26db6b2846c835b05d076631483a2a2033d088d88e95a5 (path )'}`
    - `ValueError` with message like `There are currently no blocks after 1547651804`
3. If `SCI.is_synchronized` method returns True and during method call there are different exceptions (`ValueError` with different codes and messages than those described in (2) counts in to), raise them.
4. If `SCI.is_synchronized` method returns True and during method call there are no exceptions, do nothing.

This should be checked before every call to SCI that can cause this exceptions. So far we identified that it can be caused by:
- getting list of payments.
- getting deposit status.

This can be also verified by checking old Sentry errors and see which SCI calls caused them.

**Comment by cameel** [comment]
> - `ValueError` with message like `There are currently no blocks after 1547651804` 

This case can happen also due to factors other than desynchronization. As I explained in https://github.com/golemfactory/concent/issues/1060#issuecomment-456103402 this can happen if you simply receive a timestamp that's in the future from the client.

So if the timestamp is very close to the current time or is in the future we should ignore that exception even if the client is out of sync.

> If SCI.is_synchronized method returns True and during method call there are different exceptions, raise them.

A `ValueError` caused by something else should also be treated as a different exception. Really, it would be best if SCI used a custom exception here rather than `ValueError`.

**Comment by cameel** [comment]
BTW, @rwrzesien the list in point 2) in your description is not nested correctly.

**Comment by rwrzesien** [comment]
> A ValueError caused by something else should also be treated as a different exception. Really, it would be best if SCI used a custom exception here rather than ValueError.

Yes, this is what I have meant by `during method call there are different exceptions`, but now as I have read it again it might sounds like `ValueError` with different code/message does not count here, I have updated the description.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163386324

**Comment by cameel** [comment]
> > - `ValueError` with message like `There are currently no blocks after 1547651804` 
>
> This case can happen also due to factors other than desynchronization. As I explained in https://github.com/golemfactory/concent/issues/1060#issuecomment-456103402 this can happen if you simply receive a timestamp that's in the future from the client.
>
> So if the timestamp is very close to the current time or is in the future we should ignore that exception even if the client is out of sync.

Actually your description was correct here, sorry for confusion. If `is_synchronized()` returns `True`, it's always safe to ignore this particular `ValueError`. It just means that the list of transactions is empty. If it returns `False`, we don't even call `get_first_block_after()` and return HTTP 502 immediately.

**Comment by Jakub89** [comment]
> If SCI.is_synchronized method returns True ignore exceptions raised during method call like:

What does it mean "ignore"? Return `None` will cause errors later in code. And we can't return some default values, because sci functions returns different types of values. We would need separate decorators for `get_list_of_payments()` and `get_deposit_value()`.

**Comment by rwrzesien** [comment]
@Jakub89 Good question, I haven't thought about that. I think one of the solutions would be to add a retry with timeout here too. 

@cameel What do you think?

**Comment by cameel** [comment]
For `get_first_block_after()` "ignore" means "silence the exception and behave as if it told you that there is no such block".

For `get_deposit_value()` - actually that's a good point. We can't really ignore it because we do need the deposit value. In that case let's not ignore it. It should just fail. Adding a call to `is_synchronized()` before it will make such a failure very unlikely anyway.
