### ISSUE TITLE
Missing rollbacks on HTTP 4xx and 5xx errors

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#176]
We're writing code with the assumption that all our views are wrapped in database transactions and that in case of an exception the transaction is rolled back. `ATOMIC_REQUESTS` in database settings ensures that the transactions are there but I have noticed that rollbacks are currently broken. That's because we catch exceptions ourselves in `api_view` instead of letting Django handle them.

Ensure that a HTTP 4xx or HTTP 5xx error returned to the client always involves a rollback of all the (incomplete) database changes. If necessary, roll back the transaction manually.

Review also views that do not use `api_view` such as the ones in gatekeeper.

Add a simple test that defines a view based on `api_view`, raises an exception in it and checks that changes have been rolled back. Note that this test case must be based on [TransactionTestCase](https://docs.djangoproject.com/en/2.0/topics/testing/tools/#django.test.TransactionTestCase) because the ordinary `TestCase` uses transactions as a way to quickly clear the database between test runs.

**Comment by rwrzesien** [comment]
This is how it works currently and after my changes:
- For gatekeeper, there is no concern because it is not using database at the moment. If it start, we will have to approach to it individually depending on how it will be used.
- For 5xx errors there is no problem in rollbacks as long as we have `ATOMIC_REQUESTS` set to True.
- For 4xx errors there is no problem when we don't handle errors in our own way.
- For 4xx errors which we handle (like in `@api_view`.) there was an issue, which is currently fixed by using transaction savepoint before starting a view and rolling back to it when handing 4xx error.

I have added tests if changes are rolled back for each case:
- 400 in view with `@api_view`
- 500 in view with `@api_view`
- 400 in view without `@api_view`
- 500 in view without `@api_view`
