### ISSUE TITLE
Catch UnicodeEncodeError when decoding client key.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#234]
Related with https://talkback.golem.network/sentry/concent-test/issues/32

We need to catch UnicodeEncodeError when decoding client key. Please update all places where this can happen. Please add test for each case.

**Comment by cameel** [comment]
@rwrzesien Please remember to add labels. Also try to include the important parts of the report, such as the traceback and exact error message, because not everybody who has access to the bug tracker on github automatically has access to Sentry.

**Comment by rwrzesien** [comment]
@cameel Right, traceback

```
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
utils/api_view.py in wrapper at line 36
    @csrf_exempt
    def wrapper(request, *args, **kwargs):
        if 'HTTP_CONCENT_CLIENT_PUBLIC_KEY' not in request.META or request.META['HTTP_CONCENT_CLIENT_PUBLIC_KEY'] == '':
            return JsonResponse({'error': 'Concent-Client-Public-Key HTTP header is missing on the request.'}, status = 400)
        try:
            client_public_key = b64decode(request.META['HTTP_CONCENT_CLIENT_PUBLIC_KEY'].encode('ascii'), validate=True)
        except binascii.Error:
            return JsonResponse({'error': 'The value in the Concent-Client-Public-Key HTTP is not a valid base64-encoded value.'}, status = 400)
```

**Comment by cameel** [comment]
This is not a traceback ;)

Also, all bugs should definitely be added to Pivotal so please add this one.

**Comment by rwrzesien** [comment]
> This is not a traceback ;)

Why ?

**Comment by cameel** [comment]
It's just a piece of code showing the line that triggered the exception. Pasting code might be useful in some cases too but traceback (or stack trace) specifically is a list of function calls that were on the stack where it happened:

``` python
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
  File "django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "utils/api_view.py", line 36, in wrapper
    client_public_key = b64decode(request.META['HTTP_CONCENT_CLIENT_PUBLIC_KEY'].encode('ascii'), validate=True)
```

It's generally more useful than any single piece of code because the first thing I want to know when I see an error is which pieces or our own code were involved and which one did something wrong (it's often neither the last nor the first one in the call chain).

**Comment by rwrzesien** [comment]
Yes, I know, I have already added it.

**Comment by cameel** [comment]
Oh, OK. I did not notice. We probably were writing at the same time :)

By the way, I don't think encoded messages and public keys are necessary. They would be useful if you could decode them and show the contents in a human-readable form (JSON? Python code that creates a message?) that could be analyzed by someone reading the issue. Binary form not so much because someone who does not have access to Sentry probably does not have access to the private keys either. That's obviously worth the effort only if you can do it easily or if you think they're essential to solving the problem.
