### ISSUE TITLE
TaskToCompute should be required and validated RejectReportComputedTask

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#265]
In version 2.3.1 golem message `RejectReportComputedTask` can contain:
1. `TaskToCompute`
2. `CannotComputeTask` which contains `TaskToCompute`.

Currently Concent only checks and validates `TaskToCompute` in `CannotComputeTask`. The questions are: 
1. Should Concent always expect `TaskToCompute` in `RejectReportComputedTask` ?
2. Should `TaskToCompute` in `RejectReportComputedTask` be the same as `TaskToCompute` in `CannotComputeTask`?

If any of those is true, add proper validation to `handle_send_reject_report_computed_task` and update tests.

**Comment by lukasz-glen** [comment]
An excerpt from analytic documentation.

`MessageRejectReportComputedTask. Wysyłany jako negatywna odpowiedź do Providera przez Requestora (na komunikat MessageReportComputedTask) lub poprzez usługę Concent (w komunikacie MessageForceReportComputedTaskResponse). Zawiera:`
`1. Komunikat MessageTaskToCompute.`
`2. Powód. 
a. Przekroczenie limitu czasu na obliczenie podzadania.
b. MessageCannotComputeTask, Provider wcześniej przesłał komunikat MessageCannotComputeTask, ten komunikat jest dołączony.
c. MessageTaskFailure, Provider wcześniej przesłał komunikat MessageTaskFailure, ten komunikat jest dołączony.`

1. Yes, TaskToCompute is mandatory.
2. Yes. Although CannotComputeTask is optional. And the validation should be in golem-messages because it is about the massage consistency. Moreover, the validation should also check a reason: the message CannotComputeTask is not empty if and only if the reason is GOT_MESSAGE_CANNOT_COMPUTE_TASK. The same for TaskFailure.
