### ISSUE TITLE
Concent sends BAD REQUEST when RejectReportComputedTask.cannot_compute_task is None

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#286]
The validation of `RejectReportComputedTask` is broken - when `cannot_compute_task` is `None`, then validation raises `Http400`
```python
def handle_send_reject_report_computed_task(request, client_message):
    current_time      = get_current_utc_timestamp()
    client_public_key = decode_client_public_key(request)
    validate_golem_message_reject(client_message.cannot_compute_task)
```
and 
```python
def validate_golem_message_reject(
    golem_message: Union[message.CannotComputeTask, message.TaskFailure, message.TaskToCompute]
):
    if not isinstance(golem_message, (message.CannotComputeTask, message.TaskFailure, message.TaskToCompute)):
        raise Http400("Expected CannotComputeTask, TaskFailure or TaskToCompute.")
```
According to [spec](https://docs.google.com/document/d/1QMnamlNnKxichfPZvBDIcFm1q0uJHMHJPkCt24KElxc/edit#heading=h.oy6crlu3wci4), `cannot_compute_task` can be `None`, thus validation must be changed.

**Comment by cameel** [comment]
Here are the conditions necessary for `RejectReportComputedTask` to be considered valid:
- `task_to_compute` is an instance of `TaskToCompute` signed by the requestor
- `cannot_compute_task` is not `None` if and only if `reason` is `GotMessageCannotComputeTask`
    - if it's not `None`, it's an instance of `CannotComputeTask` signed by the provider
- `task_failure` is not `None` if and only if `reason` is `GotMessageTaskFailure`
    - if it's not `None`, it's an instance of `TaskFailure` signed by the provider

**Comment by cameel** [comment]
For @rwrzesien, full `send/` logic for this use case:

#### Generic checks, common for any message submitted to `send/`
- If the message cannot be decoded or is not signed by the authorized client, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If the message is not valid (invalid field types, timestamps, missing fields, etc), Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If client's key is not in `TaskToCompute`, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 401 with appropriate `WWW-Authenticate` header.

#### Message from provider to Concent
##### `ForceReportComputedTask`
- If the client is not a provider for this task, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If the subtask is not in the `UNKNOWN` state:
    - If the subtask is already in the `FORCING_REPORT` state, Concent responds with `ServiceRefused` (`reason`: `DuplicateRequest`).
    - If we can determine (based on the subtask table) that the provider has successfully submitted `ForceReportComputedTask` for this subtask in the past, Concent responds with `ServiceRefused` (`reason`: `DuplicateRequest`).
    - Otherwise, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If `TaskToCompute.deadline` < current time, Concent responds with `ForceReportComputedTaskResponse`.
    - `reason`: `SubtaskTimeout`
    - `ack_report_computed_task`: None
    - `reject_report_computed_task`: `RejectReportComputedTask` instance with `reason` = `TaskTimeLimitExceeded`, generated and signed by Concent.
- Otherwise Concent responds with HTTP 202
    - Concent creates `ForceReportComputedTask` and adds it to requestor's receive queue.

#### Message from requestor to Concent
##### Checks common for both `RejectReportComputedTask` and `AckReportComputedTask`
- If the client is not a requestor for this task, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If the subtask is not in the `FORCING_REPORT` state, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
    - This includes the `UNKNOWN` state, i.e. subtask not present in the `Subtask` table.
- If the requestor has already submitted `RejectReportComputedTask` or `AckReportComputedTask` for this subtask, Concent responds with `ServiceRefused` (`reason`: `DuplicateRequest`) or HTTP 400.
    - This probably won't ever happen because submitting such a message should change subtask state.
- If `TaskToCompute.deadline` + CMT < current time, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.

##### `AckReportComputedTask`
- If the message does not pass consistency checks for `AckReportComputedTask`, Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
    - E.g. if `subtask_id` in `ReportComputedTask` does not match the one in `TaskToCompute`.
- Concent adds `ForceReportComputedTaskResponse` to provider's receive queue
    - `reason`: `AckFromRequestor`
    - `ack_report_computed_task`: 
    - `reject_report_computed_task`: `AckReportComputedTask` generated and signed by requestor
- Concent responds with HTTP 202

##### `RejectReportComputedTask`
- If the message does not pass our consistency checks (see my comment above: https://github.com/golemfactory/concent/issues/286#issuecomment-382001803), Concent responds with `ServiceRefused` (`reason`: `InvalidRequest`) or HTTP 400.
- If `RejectReportComputedTask.reason` is `TaskTimeLimitExceeded` or `SubtaskTimeLimitExceeded`:
    - Concent adds `ForceReportComputedTaskResponse` to provider's receive queue
        - `reason`: `ConcentAck`
        - `ack_report_computed_task`: `AckReportComputedTask` generated and signed by Concent
        - `reject_report_computed_task`: None
    - Concent adds `VerdictReportComputedTask` to requestor's out-of-band receive queue
    - Concent responds with HTTP 202
- Otherwise:
    - Concent adds `ForceReportComputedTaskResponse` to provider's receive queue
        - `reason`: `RejectFromRequestor`
        - `ack_report_computed_task`: 
        - `reject_report_computed_task`: `RejectReportComputedTask` generated and signed by requestor
    - Concent responds with HTTP 202

**Comment by dybi** [comment]
@cameel,

> Here are the conditions necessary for RejectReportComputedTask to be considered valid:

shouldnt we include the check weather 'TaskFailure' and 'CannotComputeTask' are simultanously present in the message (as discussed yesterday)?

**Comment by cameel** [comment]
That's already covered by the checks I specified:
> - cannot_compute_task is not None if and only if reason is GotMessageCannotComputeTask
> - task_failure is not None if and only if reason is GotMessageTaskFailure

**Comment by rwrzesien** [comment]
@cameel As discussed, I will point out what is not done currently:

> If the message cannot be decoded or is not signed by the authorized client, Concent responds with ServiceRefused (reason: InvalidRequest) or HTTP 400.

We currently check only if `TaskToCompute` is signed by the key it contains. I am not sure if other nested messages are signed separately (apart from the 'top' message).

> If the message is not valid (invalid field types, timestamps, missing fields, etc), Concent responds with ServiceRefused (reason: InvalidRequest) or HTTP 400.

Same here, we do precise checks only for some fields in `TaskToCompute` and `ComputeTaskDef.

> If client's key is not in TaskToCompute, Concent responds with ServiceRefused (reason: InvalidRequest) or HTTP 401 with appropriate WWW-Authenticate header.

We return HTTP 400 with error message instead of HTTP 401 in this case.

> If the client is not a provider for this task, Concent responds with ServiceRefused (reason: InvalidRequest) or HTTP 400.

How would you check this ?

> If the subtask is already in the FORCING_REPORT or REPORTED state, Concent responds with ServiceRefused (reason: DuplicateRequest).
> If we can determine (based on the Subtask table) that the provider has successfully submitted ForceReportComputedTask for this subtask in the past, Concent responds with ServiceRefused (reason: DuplicateRequest).

Currently HTTP 400 with error message. Also, currently we only check if there is a `Subtask` with given `subtask_id`, but I think it covers both cases.

> Otherwise, Concent responds with ServiceRefused (reason: InvalidRequest) or HTTP 400.

We are not doing this now.

> If TaskToCompute.deadline < current time, Concent responds with ForceReportComputedTaskResponse. reason: SubtaskTimeout
> Concent adds ForceReportComputedTaskResponse to provider's receive queue reason: AckFromRequestor
> Concent adds ForceReportComputedTaskResponse to provider's receive queue
reason: ConcentAck
> Concent adds ForceReportComputedTaskResponse to provider's receive queue
reason: RejectFromRequestor

We are not setting reason now, and we don't have option to do so - we would have to provide extra types for `PendingResponse`, which would determine combination of type and reason.

Please remember we need extra test(s) for each case.
