### ISSUE TITLE
Some message validators don't have enough information to return meaningful errors

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#394]
Currently `validate_all_messages_identical` and `validate_golem_message_signed_with_key` are raising HTTP400 error when the validation fails. This disallows flexibility in using those functions. Instead, they should:
* validate_all_messages_identical - return which fields doesn't match, then raise http400 in the place where function is called.
* validate_golem_message_signed_with_key - return True/False, then raise http400 in the place where function is called (done in https://github.com/golemfactory/concent/pull/513).

**Comment by pawelkisielewicz** [comment]
I don't understand the point of task. Now we have validation functions that raises exception if verification fails (BTW i think it should be something like `ValidationError` or `ValidationMissmatch`, not `http400`). 

What is the purpose of this?

Now it works like 'normal' validation function and it's call needs one line in our code. If i change it will require:
1. call function
2. check if there are not matching fields
3. create and raise exception

As it is like now points 2 and 3 are written once in validation function. Are you sure we want to move point 2 and 3 to all places where function is called? Now all information (including which fields are not matching) are saved to exception inside validation function and raised.  

I think the best idea is to change `http400` to other `error` or `exception` and reformat or add something to message if needed. What do you think?

**Comment by rwrzesien** [comment]
Reopening because github closed automatically, but it is only partially done.

**Comment by rwrzesien** [comment]
Updating description about `validate_golem_message_signed_with_key` being resolved in https://github.com/golemfactory/concent/pull/513.

**Comment by rwrzesien** [comment]
@pawelkisielewicz To move the exceptions which should be raised in the views, back to the views. But raising one of the exceptions you have proposed is a good idea too. However we should be consistent all over. Currently most of validators raise `http404` so I guess we want to refactor them to new approach of our choice. I will add issue of both to discuss for the team in our coding style repository.

**Comment by rwrzesien** [comment]
This issue is extended by https://github.com/golemfactory/concent/issues/593, so I am closing this one.

**Comment by cameel** [comment]
> I don't understand the point of task.

I'm not sure if the work on this task went in the right direction. The point was that we had a validating function that received a set of values as input and raised an exception saying that the message containing them was invalid. But how could it even know if the values actually come from a message? As a result the error message did not make sense in some places where that function was being used.

@rwrzesien Has this root issue been fixed? I still see a similar pattern being used in new code, e.g. in: https://github.com/golemfactory/concent/pull/678#discussion_r204715088

**Comment by rwrzesien** [comment]
@cameel I think the root issue was to get rid of `Http400` errors being raised directly by validators. It was replaced by `ConcentValidationError` but it contains error code, and this exception is caught directly in view decorator and changed into `JsonResponse`. Changing it in a way that every call to validation function should try/except and handle `ConcentValidationError` and add error code itself would be a lot of work. But I get your point. However, please note that a lot of validation functions operate directly on the message so using error code there is justified. We can discuss how to proceed with this.

**Comment by cameel** [comment]
The root issue (at least the issue I pointed out in one of the reviews and which resulted in the creation of this task in Pivotal) was the error message itself and that it can't be properly constructed inside a nested validator that does not know where the data it validates comes from.

It was that instead of this:
- Validate x
    - Validate x.y
        - Validate x.y.z

where each level can independently raise the final exception and has to construct the whole message, we should have something like this:

- Validate x
    - Is x.y valid?
        - Is x.y.z valid?

where only the top level raises exceptions. Lower levels either return only `True`/`False` or give us partial message that can be enriched with additional information at the top level. This partial message can actually be passed to the top level using exceptions but those intermediate exceptions should be intercepted there and replaced with the final exception containing the full message and error code.

That's how the functions we created initally worked (`True`/`False`) and that's how for example Django's validation system works (partial messages, intercepting exceptions).

For reference, link to further discussion on the subject: https://github.com/golemfactory/concent/pull/678#discussion_r205065010.
