### ISSUE TITLE
Ensure that the same subtask is never processed by two processes in parallel

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#412]
Ensure that the `send()` view, Celery tasks in `concent-worker` and the function for enforcing timeouts never run in parallel for the same subtask. If one of them is working on a subtask, the others should wait.

Use database locks to achieve this. When one of those pieces of code starts, it should lock the corresponding row in the `Subtask` table. If it's already locked, it should retry a few times with some delay in between. Eventually it should give up and fail. The time after which it gives up should be configurable (but use a sensible default). Also, make sure that Celery tasks that fail are retried. And that we get a Sentry notification when one fails permenently (fails so many times that Celery stops trying).

Make sure that the code releases the lock if it fails. Use a `try ... finally ...` block for that. This does not guarantee releasing it in all cases - for example if the process simply crashes (hard crashes, not just raises an exception) before it gets to the `finally` part. But this should interrupt the session and cause a rollback that releases the lock. Make sure that this is the case.

**Comment by pawelkisielewicz** [comment]
After discuss with @cameel, the best approach to do this task is to use database savepoints and locks. 
Using `select_for_update` for subtasks requires, that subtask exist (this `lock` will not be started, if `subtask` does not exist).

We should prevent errors from database by saving (commiting) `subtask` to `database` just after create (we use `ATOMIC_REQUESTS`, so the changes are commited to `database` at the end of atomic transaction- at the end of whole functions (incl. decorators)). In case there are two the same subtasks processed in one time (and they are not in `database`, will be created with the same id), one of them will be saved (normal, positive scenario), and the second one will fail. In this case we should catch the exception and simply use `get` instead of `get_or_create`.   

After this we can lock database for particular subtask, in this moment we are sure that `subtask` exist in database. We must ensure release of `database lock` and commit changes to database at the end of function. 

In worker case, there will be only `database lock` required. There the subtasks are only updated (not created), so they always exist

**Comment by rwrzesien** [comment]
Where do you want to start and release locks ?

**Comment by pawelkisielewicz** [comment]
In workers the whole functions should be locked. 

In core/send `lock` should start just after `"get"` a `subtask`. `"get"` is a section of getting or creating subtaks (second paragraph) and when we have subtaks in database (commited to database) `lock` starts. In this case `lock` ends at the end of view

**Comment by pawelkisielewicz** [comment]
Small update for views: If function is locked, process is returning back to beginning and again validated. In some cases it is important, sometimes we expect e.g. `ServiceRefuse` instead of processing

**Comment by cameel** [comment]
This sounds really risky. This could lead to stuff being done more than once. Let's talk about it tomorrow.

**Comment by cameel** [comment]
I'm closing this issue because the description no longer precisely describes what needs to be done. I am creating a series of issues that will address the problem and also new problems that became apparent during work on this one.

#718 is enough to cover almost everything this issue was meant to accomplish.

The problems that will be covered by other issues:
- We need retry if there are two simultaneous attempts to create a subtask (#486).
- Payments cannot be nested inside a transaction because `DatabaseTransactionsStorage` needs to be able to commit (a savepoint is not enogh).
- Timeout processing at the beginning of `send/` and `receive/` views needs to be in a separate transaction to prevent the views from keeping locks on unrelated subtasks longer than necessary.
- We should always perform any operations that cannot be rolled back (blockhchain payments, adding tasks to Celery queue, modifying files, etc.) after any changes in the database are done and committed.
