### ISSUE TITLE
ForceSubtaskResults window problem

### ISSUE THREAD

**Issue by jiivan** [golemfactory/concent#426]
It looks like either
 1. Window is calculated differently in Golem and in Concent
 1. Time is desynchronized

Sent:
```
ForceSubtaskResults(header=MessageHeader(type_=4015, timestamp=1527259088, encrypted=False), sig=b'\xa9\xa9\x8c\xbfq\xbf\x94c+\xce\xfb\xa5\xfa\xf9\xb1)\xfb\x9d\x8e\xe7\xa0\xd9d\xf2o4\xc3x\xef\xf4\x9a&|E]\xfcC\x8fy\xb2\xb1\xbe\xbc\xe9\xc1\x99\x87\xa6\xe7b\xee\xbdd\xe1P\xaa\x1cC\xd8\x91\xf0\x0b\x04\t\x00', slots=[['ack_report_computed_task', AckReportComputedTask(header=MessageHeader(type_=2029, timestamp=1527259088, encrypted=False), sig=b'{\x9c\x9d3`~r[\x10\xf6\xc0\\\x0fTc(\xb4\x11\x16\xb3\xa0h\xe2\xa8\xdc\xd8\xf28\xe2\xe5b\x8eD\xefS\x97.\x11\x10\xcca\xf8\x00\x9eb\x17\xca\xb8\xe6\x19\x1e\x03M\xd5\xb7\r\xcc\xcaj\xea".\xbf\x9d\x01', slots=[['report_computed_task', ReportComputedTask(header=MessageHeader(type_=2004, timestamp=1527259088, encrypted=False), sig=b"x\x8d\x8a\xdd\xa2\x80\xd2\xd1\xa9e\x04p\x0c\xe4\x1d\x0e\xff|\x1f\xe6'\xc79>\xe9\xa6%\xe2\xab\x93\x08\xf1\x1c\x80&\x14\xc9\x96[\xd5|r\xd3{IU\x0c\x9f\xfd#\xbe\x00\xd6\xf0\x95\xd7\xb3\x03#\xbe\x13\xad\xb3E\x01", slots=[['result_type', 0], ['node_name', 'Charles Carter'], ['address', '162.234.157.62'], ['node_info', None], ['port', 8899], ['key_id', b'A-\xf0|F\xd4\x89\xd9\xec@^8H\x90\x89l\x80q\x8f\x81m\xc0\xdf\xc9|z\xe9\x9c\xf2\xd2\xdf!\x91\xa6nRD\xac\xfb\x85]D\xb5.&a\xe6\x00\x894^\xcd\xb1\x08\xed9\x9f\x17\x973OBh\x1d'], ['extra_data', None], ['eth_account', '0x40c5c4e37a3904f53742ba608e7d066b2349cb63'], ['task_to_compute', TaskToCompute(header=MessageHeader(type_=2002, timestamp=1527242155, encrypted=False), sig=b"Sli\xbb\xc5\xf0x\x81\x08l\xf2E\x03.\xea\x98'\xf4\x06\x98\x88\x8dj>\xe4\xee\x12\x9fiX\xa1\xc1u\xd1\x0e\x9ak\x8c\xbe\x9e\x83\xa8I\xd5\xba\xab\xb1\xb6w\x19\x9a\xe2b\xe3[\xd3%\xd9}\x9fg\xcf\xee\xd3\x01", slots=[['requestor_id', b'eQ\xa5\x8c\x14\xa0\x19\xec``\xff\x17N#L(um@\xe8Rt\x80\xa67R\xec\xf3x\xd4\x0e=\x12Q\xd4\xc6\xecO\xc5]\x8a\xf0\x07\xcf\xb7\xb1\x0e\xdb\x96Onl\xce|%k\x83\xcf\xdc\x86\x08\x84\xa5x'], ['requestor_public_key', b'G\xa0p\x04\xdd\xde\xdf\x99\xb9\xfe\xc6\x1b@\x9d\xe6\xe81zKB\xc8$o\xfd\x11XQ\xf0\x1e3D0i\x1e\x8e\xed\x16S\xc5\xd0\x81$0-\x1aE\x10m\xf2\n\x93\x88\xb5\x15\x9eO\xf5W\xbeOs\x16$\x9c'], ['requestor_ethereum_public_key', b'G\xa0p\x04\xdd\xde\xdf\x99\xb9\xfe\xc6\x1b@\x9d\xe6\xe81zKB\xc8$o\xfd\x11XQ\xf0\x1e3D0i\x1e\x8e\xed\x16S\xc5\xd0\x81$0-\x1aE\x10m\xf2\n\x93\x88\xb5\x15\x9eO\xf5W\xbeOs\x16$\x9c'], ['provider_id', b'\x10\xe2cS\x01\xcc\xbe\x98\xcc\x91\xabb\x81hb\t\xef=O\xadwX\xc5\xb3aN\xb7\xf49\xe0\xd8Ht\xe7D\xce\xfee#MZ\x95\xee\xfe\x17a\xf9x\xf9\x02Im\x87\xe5\x88g\xae\x00\xbd\x95$\xb2\x8b\r'], ['provider_public_key', b'\x08\xdb\xd9\xd3e\x82T"\xc6;a\xb4\x84\xe8\xd6\x8d\xda(mz\x05\xedfW\x19\\I\xb5\xee\xd0\xf5\x98y\xb5\\J\xbcb\x9fp\xe7\x03\x1d\xe6r\x99\x80\xfd\xf2\x03gp\x0b)\x9e \xceR\x9c<A\t\xb2r'], ['provider_ethereum_public_key', b'\x08\xdb\xd9\xd3e\x82T"\xc6;a\xb4\x84\xe8\xd6\x8d\xda(mz\x05\xedfW\x19\\I\xb5\xee\xd0\xf5\x98y\xb5\\J\xbcb\x9fp\xe7\x03\x1d\xe6r\x99\x80\xfd\xf2\x03gp\x0b)\x9e \xceR\x9c<A\t\xb2r'], ['compute_task_def', {'task_id': '44175b4f-6096-7a91-2bbd-051512a63316', 'subtask_id': 'd7983c17-e69b-e8b8-f5a5-63349e6cc52a', 'deadline': 1527245755, 'src_code': 'Early character back watch politics end trouble two. Decision somebody forward contain long share. Hold even bank whether. Entire main fear nation law expert.', 'extra_data': {}, 'short_description': '', 'working_directory': '', 'performance': 0, 'docker_images': None}], ['package_hash', 'sha1:3c986a701778550f29332979311733d7790cd797'], ['size', 10081531], ['concent_enabled', True], ['price', 7790931]])], ['size', 9005943], ['package_hash', 'sha1:6a0fbec8268db0ba897f2d37259948fb9ebc803d'], ['multihash', 'Write lot stay few party must total. Situation national special PM crime leader store.'], ['secret', 'Check and popular under spend meet. Stop those ask reality quality star. Establish hope like. Leader tree assume sport born second.'], ['options', None]])]])]])
```

Received:
```
ForceSubtaskResultsRejected(header=MessageHeader(type_=4017, timestamp=1527259452, encrypted=True), sig=b'\x96\xb1\xc4\xa3\xcb\xaf\x9d+\xf0\x99H\xe9f\xc9\xbbTs\x02\x8f\x8cs\xad7\xbb\xc5u\xdf\xcd~\x02\xd2\x0b;\xe6}\x9a\xdd\x82\x91\xf4.\xb1\xdb\x1a\xc6\x02\xa2\xcd&\x00/\xa8\xd7\x89\xd1\xa0\xa2\xd0\x1eEN\x15\x1a\xb7\x01', slots=[['force_subtask_results', None], ['reason', 'premature: still within the verification timeout']])
```

Steps to reproduce:
`pytest scripts/concent_integration_tests/force_accept/test_requestor_doesnt_send.py -sl --maxfail=2 -k test_already_processed`

Please use https://github.com/golemfactory/golem/pull/2818

**Comment by rwrzesien** [comment]
I will take a look on this in nearest possible moment.

**Comment by rwrzesien** [comment]
Assuming that 
- the request is sent on timestamp 1527259088,
- the environment on which this is tested is our staging, where following time settings are:    
    CONCENT_MESSAGING_TIME = 3600
    FORCE_ACCEPTANCE_TIME = 14400

the reason for this reject is because this condition is met:
`if forcing_acceptance_deadline < current_time`

`forcing_acceptance_deadline` is `compute_task_def['deadline'] + calculate_subtask_verification_time(client_message.ack_report_computed_task.report_computed_task)`

`calculate_subtask_verification_time(client_message.ack_report_computed_task.report_computed_task)` is our custom implementation of `golem_messages.helpers.subtask_verification_time`, but in this case (as they should always do) both return the same results:

calculate_subtask_verification_time(report_computed_task) => 16932
subtask_verification_time(report_computed_task).total_seconds() => 16932.0

Summing it up, if the described logic is ok, it looks like the request is sent before `deadline + subtask_verification_time` has passed.

**Comment by rwrzesien** [comment]
@jiivan Actually, what is expected result ? The bug is about that you have received reject, or a reject with wrong timestamp ?

**Comment by cameel** [comment]
@rwrzesien The issue is that Golem's test case is failing. Since @jiivan says that windows may be calculated wrong I guess it fails because it does not expect a timeout in the situation it's testing. Please run Golem's test suite on your machine and investigate what it assumes and whether its assumptions are correct according to our knowledge.

@jiivan Looks like @rwrzesien is right here. Concent's response seems correct according to timing values from golem-messages and @lukasz-glen's spec. 

The situation looks like this:
```
TTC.timestamp             = 1527242155 = TTC.timestamp +     0
TTC.deadline              = 1527245755 = TTC.timestamp +  3600
RCT.timestamp             = 1527259088 = TTC.timestamp + 16933
FSR.timestamp             = 1527259088 = TTC.timestamp + 16933
TTC.deadline + SVT        = 1527262687 = TTC.timestamp + 20532
TTC.deadline + SVT + FAT  = 1527277087 = TTC.timestamp + 34932
```

The FSR comes before SVT which is too early. @lukasz-glen's spec (page 21) has a diagram that shows that the provider should not be able to force acceptance before SVT. We enforce this lower limit because otherwise the requestor may not have enough time to do his own download and verification.

I just spotted one discrepancy with the spec though: we agreed with @lukasz-glen that to work around one of the corner cases all time windows should start at `TTC.deadline`, not `RCT.timestamp`. But the spec still states the latter. Maybe this is the problem?

**Comment by cameel** [comment]
> What is bothering me is why there is so big gap (364 seconds) between `ForceSubtaskResults` timestamp and `ForceSubtaskResultsRejected` timestamp ? Concent responds immediately.

No, it doesn't. Concent generates the response when client comes for it. So if the client asks for it 364 seconds later, the timestamp can be 364 seconds away from the initial request.

**Comment by cameel** [comment]
I think I have just spotted the source of problem. SVT (16932 seconds) looks suspiciously close to FSR.timestamp (16933 seconds). I think that Golem incorrectly assumes that the window starts at TTC.timestamp + SVT rather than at TTC.deadline + SVT.

**Comment by jiivan** [comment]
Thanks @rwrzesien & @cameel ! You were right, I lost `TTC.deadline` somewhere in the formula.
