### ISSUE TITLE
Update golem_messages version in Concent from v2.9.0 to v2.9.4

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#434]
We need to update golem_messages version in Concent from v2.9.0 to v2.9.4.

Release notes for this version:
https://github.com/golemfactory/golem-messages/releases/tag/v2.9.4

One of the known things to do is that fields `requestor_id`, `requestor_public_key`, `requestor_ethereum_public_key`, `provider_id`, `provider_public_key`, `provider_ethereum_public_key` will now contain `str` which is result of `binascii.hexlify()` function instead of `bytes`. This will result in
- updating validation of those fields,
- update in tests (integration and cluster), where factories are not used.

Other problems are difficult to predict, so if any questions arise please add them to this issue.

**Comment by kbeker** [comment]
@rwrzesien I am not sure if we need to change `provider_ethereum_public_key` and `requestor_ethereum_public_key`. Just look at this piece of code:
```python
    @property
    def requestor_ethereum_address(self):
        return '0x{}'.format(
            sha3(self.requestor_ethereum_public_key)[12:].hex(),
        )

    @property
    def provider_ethereum_address(self):
        return '0x{}'.format(
            sha3(self.provider_ethereum_public_key)[12:].hex(),
        )
```
These are properties `TaskToCompute` message and to get eth addresses they need to get `ethereum_public_keys`. This will completely change ethereum addresses. Just look:

```python
>>> sha3(public_key)[12:].hex()
>>> 'a9d2dd606897616870cf58baca26d7bf23dd3407'

>>> sha3(public_key.hex())[12:].hex()
>>> '01749c4e08f6852863dd4b7024eb2a1c8b5a0268'
```

I think it might be a problem and we should discuss it

**Comment by kbeker** [comment]
After discuss with @cameel and @rwrzesien we decided that we need to create new helper which will convert hex value into bytes. Thanks to this we can avoid much of changes in core model, message handler etc. So, @pawelkisielewicz : 
- change our test utils to pass in `TaskToCompute` requestor_public_key, requestor_id, provider_public_key and provider_key as hex - you don't have to generate new keys - just use old ones and convert these bytes into hex and pass to TTC message
- add unit tests to this function, because we need to be sure that it works properly
- find places where we use public keys from TTC and put on this keys function to convert bytes->hex
- look through every test where we use `TTC` and check if there is any place where we add parameter `requestor_public_key`, `requestor_id` etc. to function which creates TTC - it should get this parameter directly in utils - perhaps you want to test some case where you want to change public key - than it should stay as it is. It is good moment to repair this in our tests because we add this at very beginning and we never fixed it 
- add asserts to convert function to be sure that everything works fine
