### ISSUE TITLE
Handling duplicate upload acknowledgements from the control cluster

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#472]
`upload_acknowledged` queries for `VerificationRequest` with given `subtask_id` and changes `VerificationRequest.upload_acknowledged` to `True`.

Before doing it check if it's already true. If it is, raise an exception.

The exception should be reported to Sentry. But don't do it manually. When #511 is implemented it will start happening automatically.

**Comment by cameel** [comment]
Description updated. I think that we should be raising an exception if it's already true. That's because there's no situation in which it's supposed to happen. It can happen only if something fails and is retried but we've decided to deal with such situations later, when all use cases are done. It's not needed in the initial version.
