### ISSUE TITLE
TaskToCompute.compute_task_def['deadline'] is float

### ISSUE THREAD

**Issue by jiivan** [golemfactory/concent#54]
In current golem core `ComputeTaskDef['deadline']` is `float`, but concent fails with:
```
Concent request failed with status 400 and response: '{"error": "Wrong type of deadline field."}'
```

Ideally validator should try to cast `deadline` to int and only raise exception if it fails.

**Comment by cameel** [comment]
@jiivan OK. In general I prefer to avoid implicit conversions and be strict about types. Sometimes blindly converting stuff leads to a case where an obviously wrong value that should just make the code fail is converted and goes through silently still yielding wrong results. But in this particular case I don't see anything that could cause problems. `int()` supports only numbers and strings so we're covered.

One downside is that we'll have to remember to call `int()` every time we access a `timestamp` field which is error-prone. Maybe it would be a good idea to add a property on `Message` that performs the conversion internally?

**Comment by jiivan** [comment]
@cameel _Be conservative in what you send, be liberal in what you accept_ :) Correct me if I'm wrong, but only use for this field is to compare it to current timestamp. It will work with any permutation of ints, floats and decimals. It will even work with `decimal.Decimal('infinity') :)

**Comment by cameel** [comment]
But I did agree with you in my post above :) I meant that I don't see any problems with changing our code to do what you propose and we can modify it to add `int()` conversions. I just started by explaining that it's not my default approach because I prefer to have as many checks as possible to detect potential issues early. But conversions in this particular case seem harmless and even useful.

So what do you think about replacing `Message.timestamp` with a property and adding the conversion there? I agree that this coversion is a good idea but I think that requiring the user of the library to do this explicitly will lead to people forgetting about it.

**Comment by jiivan** [comment]
`Message.timestamp` is int since https://github.com/golemfactory/golem-messages/commit/572b11ab87fc249901012ad4443251764dc80d82 but I believe it's outside of scope of this issue.

`ComputeTaskDef['deadline']` is float though. What I meant is that you don't even have to convert it to anything. You can just verify that it's some kind of a number. And I agree that verification should be a part of golem-messages.

**Comment by cameel** [comment]
This is now fixed. It did not make it into v0.2 but will be included in the next (minor or major) release.
