### ISSUE TITLE
Concent API should validate source_package_path and result_package_path length or allow longer length in database model

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#598]
Currently Concent API build `validate source_package_path` and `result_package_path` length using `f'blender/{category}/{task_id}/{task_id}.{subtask_id}.zip'` pattern. But both `task_id` and `subtask_id` maximum length is 128 chars, so maximum length of this path is way beyond 255 limit of related fields in `VerificationRequest`. This can easily lead to validation error on Conductor `blender_verification_request` task. Also, path in `UploadReport` model has the same problem.

So Concent should either validate if built  `validate source_package_path` and `result_package_path` length is lower than set on the `VerificationRequest` and `UploadReport` models fields or allow those fields to have bigger length.

**Comment by cameel** [comment]
In the short term: Change 255 to something bigger so that there's no chance that 128-char IDs make this validation fail. 1000 should be enough (but make sure that the filesystem and the server supports paths/URLs that long).

In the medium term: Lower the maximum length constraint for `task_id` and `subtask_id`. They will never be 128-characters long now because Golem is mandating them to be 16-byte UIDs. Check if Golem has introduced this change already and update validations and constraints on our side to match.

**Comment by Jakub89** [comment]
From what I was able to find:
https://code.djangoproject.com/ticket/14094
max length of `CharField` is dependent on database we are using. MySQL, Postgres, SQLite is 65K bytes. Maybe someone, someday will want to run concent on Oracle DB which allow 4000 bytes, so 1000 characters shouldn't be a problem.

**Comment by rwrzesien** [comment]
@Jakub89 I am not sure if this will not cut data to 255 when saving. Best option for longer strings is using `TextField`.

**Comment by Jakub89** [comment]
It didn't cut data, but django still can't save `CharField` longer then 255 characters. I found this: https://groups.google.com/forum/#!topic/django-users/rRaMzqhBLg8

**Comment by rwrzesien** [comment]
Ok, then its good that you have tested it, use `TextField` then.
