### ISSUE TITLE
Refactor integration tests

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#70]
Our tests base is growing pretty fast and we need to take a wider look on how they are written.  If we do this now, we can add next tests in more efficient way. Generally I have identified following issues:
1. We are mixing use-case specific test generic tests (lets call this way tests which are not message-specific). We should move generic tests to a separate test case class (and most probably file) and refactor them to use most generic message (I think `Ping` is good candidate). This is partially resolved by @Jakub89 in https://github.com/golemfactory/concent/pull/68. Maybe `test_core_views.py` is were they should belong ?
2. Tests have a lot of repeatable code. We should group those into functions and parametrize as much as possible. This should be divided into two groups:
2.1. General utils for tests, like prepare requests, handle keys, prepare timestamps etc.
2.2. Message prepare specific function, like ie. creating ForceReportComputedTask and all messages which are required for it.

This can be realized using custom test case, a draft of it is currently done in `core/tests/utils.py`.

Perfect test case might look like:
``` python
def test_provider_forces_computed_task_report_and_requestor_sends_rejection_due_to_exceeded_deadline(self):
    """ comment """
    response = prepare_and_send_force_report_computed_task(
        task_id,
        deadline,
        freeze_time_at,
        # any other necessary params
  )

    self.assertEqual(response_1.status_code,  202)
    self.assertEqual(len(response_1.content), 0)

    OR 

    self.assert_force_report_computed_task_correct(response)

    response = receive_by_requestor()
    self.assert_force_report_computed_task_correct(response)

   etc...
```

I know @cameel that you were not fan of grouping asserts part into functions, but roughly 80% of them are the repeated, and other 20% can be grouped too using parameters. Generally a mini test framework was something I saw being added sooner or later to every bigger project.

3. Rethink if current test placement in directories is ok.
4. Add tests to reach 100% coverage and stick to it (current numbers are pretty good, but why not ? We are not far from there at the moment and it would be easier to stick to it then reach it after more code will be put into repository).
5. Check if tests in `test_core_views.py` are not duplicated by other use-case specific tests.
6. Use factory-boi for objects creation.

**Comment by cameel** [comment]
I completely agree. There's a lot of repetition in our tests that we can safely eliminate.

A custom test case is a very good idea. We had one specifically for testing JSON APIs in earlier projects.

I think we should do this in stages because otherwise we'll block development just like it was with other refactoring so far. Let's do it like this: instead of making a lot of changes at once, create a minimal test case first and then let's incrementally add new features there and refactor tests to use them. Each change in a separate pull request so that you don't have a big pile of code that you have rebase and rewrite constantly on top of new features of Concent. This will also make it easier and quicker to review and we'll be sure that our tests keep doing what they're supposed to do.

> draft of it is currently done in core/tests/utils.py.

We should move it to `core` or `utils`. `tests/` directory is just for use cases. All the related utilities are normal code and should be outside. Also, we should probably have tests for it too.

> I know @cameel that you were not fan of grouping asserts part into functions,

This needs some clarification. It's not that I don't want asserts to be ever grouped together. I do want that. I just don't want a situation where you have a bunch of unrelated checks grouped into a single function just because they happen to be used together in a test. The test should be as self-contained as possible because this allows you to understand and it and have confidence that it's checking what it should be checking without having to put several different pieces together in your head. So it's OK if you can group test assertions into coherent functions with a name that explains what you're checking. It's bad if you just call it `check_response()` and drop all assertions inside indiscriminately. Even worse if `check_response` checks different things in different test suites. Also bad if your functions access data on `self` under the hood rather than getting them via parameters.

I am all for creating helper assertions. But these assertions should be common for all tests (best defined in a custom base test case like you suggested) and have clearly defined scope reflected by their name. It should be possible to understand what they're checking just by looking at their names.

See my example below.

### Example: bad vs good refactoring in tests

Below is an example of a situation I want to avoid. Note that the test methods are very clean and short. They're also completely devoid of any information on what they're doing which makes understanding them hard. All the important differences that should stick out at you immediately are hidden away: 

``` python
def setUp(self):
    self.urls = {
        1: reverse('send'),
        2: reverse('send'),
        3: reverse('receive'),
    }
    self.data = {
        'id':  14,
        'foo': 'abc',
        'bar': 42.0,
    }

def prepare_test(self, test_id):
    if test_id == 2:
        self.data['foo'] = 'def'
    elif test_id == 3:
        self.data['new'] = 123

    return self.client.post(self.urls[test_id], self.data).json()['response']

def check_test(self, test_id, data):
    self.assertEqual(data['id'],  self.data['id'])
    self.assertEqual(data['bar'], self.data['bar'])

    if test_id == 1:
        self.assertEqual(data['foo'], 5)
    elif test_id == 2:
        self.assertEqual(data['foo'], 'abcd')
    elif test_id == 3:
        self.assertEqual(data['new'], 456)

def test1(self):
    data = self.prepare_test(1)
    self.check_test(1, data)

def test2(self):
    data = self.prepare_test(2)
    self.check_test(2, data)

def test3(self):
    data = self.prepare_test(3)
    self.check_test(3, data)
```

The example below is what I prefer instead. Even if the test methods are longer and have some repetition, they have all the details necessary for you to understand each case.

``` python
def send_message(self, message)
    response = self.client.post(reverse('send'), message)

def receive_message(self)
    response = self.client.post(reverse('receive'), message)

def assert_constant_fields_unchanged(self, response, message)
    self.assertEqual(response['id'],  message['id'])
    self.assertEqual(response['bar'], message['bar'])

def test1(self):
    message = {
        'id':  14,
        'foo': 'abc',
        'bar': 42.0,
    }

    response = self.send_message(message)

    decoded_response = response.json()['response']
    self.assert_constant_fields_not_changed(decoded_response, message)
    self.assertEqual(decoded_response['foo'], 5)

def test2(self):
    message = {
        'id':  14,
        'foo': 'def',
        'bar': 42.0,
    }

    response = self.send_message(message)

    decoded_response = response.json()['response']
    self.assert_constant_fields_not_changed(decoded_response, message)
    self.assertEqual(decoded_response['foo'], 'abcd')

def test3(self):
    message = {
        'id':  14,
        'foo': 'abc',
        'bar': 42.0,
        'new': 123,
    }

    response = self.receive_message(message)

    decoded_response = response.json()['response']
    self.assert_constant_fields_not_changed(decoded_response, message)
    self.assertEqual(decoded_response['new'], 456)
```

I think this code is uglier. But it's still better. We should make it less repetitive but only if we can do it without hiding the important details.

**Comment by rwrzesien** [comment]
Added info about factory-boi usage.

**Comment by Jakub89** [comment]
This looks like a very outdated issue. Tests in general come a long way since January 2018. If some refactor is still necessary, new issue for specific test case should be created.
