### ISSUE TITLE
 Validator for scene_file field in Compute Task Def must be more restrictive

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#716]
For this moment we validate only that if scene_file ends with `.blend`. This is much too weak validation. 
At first we should agreed on how we want to pass `scene_file` in ComputeTaskDef. 
- Should there only be relative path to file which is in archive?
- Should it be somehow related with `working_directory` which is also in ComputeTaskDef?

@cameel @rwrzesien @dybi Please add your ideas to do stronger validation for this.

@shadeofblue @jiivan please tell us how Golem pass this field to Concent

**Comment by rwrzesien** [comment]
Isn't it that placing correct `.blend` file is in the interest of provider ?

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159649324

**Comment by cameel** [comment]
Yeah, it is. If he places it in the wrong place and we don't find it, it's his fault. But this issue is about how the location is defined in the first place. Right now we assume that anything goes and this is too permissive. For example what happens if the path is `/etc/passwd`? In general absolute paths should probably be forbidden. But if Golem is allowing them then we may have to allow them in some cases, and convert them to relative paths internally. E.g. if the path starts with `/home/`.

In any case, `TaskToCompute` that does not meet the requirements should be rejected by validations. We should not even bother starting verification if we can immediately see that something's wrong with the message.

**Comment by shadeofblue** [comment]
@cameel @kbeker @Jakub89 re: the path that the `scene_file` points to relates to a directory within the Blender's docker environment

**Comment by shadeofblue** [comment]
though, there's also the `path_root` which is the directory in which the original task resides -> though I'm unsure if it's needed from Provider's POV

**Comment by PaweuB** [comment]
@shadeofblue Please provide some examples with that kind of path.

**Comment by shadeofblue** [comment]
```'scene_file': '/golem/resources/wlochaty3.blend'```

**Comment by cameel** [comment]
Thanks for the info. So, to summarize the current situation and the solution we want:
- `TaskToCompute` contains an absolute path like `/golem/resources/wlochaty3.blend`.
- The archive contains a file called `wlochaty3.blend` in its root directory.
- Therefore `/golem/resources/` is a constant part that must be the same in every `TaskToCompute`.
    - We should validate that it's present.
    - We should strip if from the path and internally only pass around the relative part (`wlochaty3.blend`).
- `/golem/resources/` is probably hard-coded in the docker image. But it could change in the future. If it changes we will have to support both the new and the old prefix.
    - We can ignore it for now and only add code to handle it when/if it happens.
    - Alternatively, we could prepare for it immediately. Have a list of prefixes (instead of just one) and accept all of them as valid.
        - Be careful about the case where one prefix is a prefix or another (i.e. `PREFIXES = ['/abc/def/ghi/', '/abc/def/']`) because this will make it impossible in some cases to say which one was used.
