### ISSUE TITLE
Use SELECT FOR UPDATE to prevent lost updates

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent#718]
This is another attempt at solving #412. The solution proposed here is simpler in many ways (no retries, not need for `finally`) but also broader in scope (applies to more than just `Subtask`) so I think it's betterto close that previous issue instead of rewriting the description and leaving a confusing thread of comments. The issue addresses the same underlying problem though.

Due to the broader scope, solving it will also solve #4.

### Overview
This article presents the problem and the solution really well: [A beginner’s guide to database locking and the lost update phenomena](https://vladmihalcea.com/a-beginners-guide-to-database-locking-and-the-lost-update-phenomena/).

The solution is simple: find every place in our code where we update an existing object (database row) and make sure that the data that is saved was fetched using `SELECT FOR UPDATE` and not a plain `SELECT`.

### Details
Until now our strategy was a little confused because I assumed that update operations do not lock the updated row until the end of transaction and that `select_for_update()` adds an overhead that we did not previously have and should be used sparingly. Turns out that we're already implicitly locking rows so there's not that much difference if we lock a little earlier.

Unlike in #412 we're not going to deal with timed out locks and retries here. Locks do not time out if we don't use `nowait=True` (they could but [`lock_timeout` in PostgreSQL](https://www.postgresql.org/docs/current/static/runtime-config-client.html#GUC-LOCK-TIMEOUT) is disabled by default).

For this reason automatic retries on locks are not necessary. We may need retries on creation operations to prevent problems like #486 but we'll deal with that in a separate issue. `INSERT`, unlike `UPDATE` is not a problem because two simultaneous creations will fail due to `UNIQUE` constraints on the primary key and the only reason for the retry is to complete the operation without returning HTTP 500 and having the client retry by itself. There's no risk of overwriting anything.

So in this issue we simply need to review our update statements. This applies not only to `Subtask`. There are several situations where we need `select_for_update()` (the list is not exhaustive):
- When marking pending responses as delivered in `receive/`.
- When updating `UploadReport`s in the `storage` database.
- When updating `upload_finished` flag in the `VerificationRequest`.

**Comment by pawelkisielewicz** [comment]
All our requests in send concern particular subtask or more than one subtask (ForcePayment). In first pull request I created lock for core/send. 
I think I did it as simple as possible, creating lock at the beginning of `handle_message`. I left view as transaction, but started lock at the beginning, before validations of particular messages. In this case there is no repeating and no danger of sending multiple HTTPs or celery tasks and no nested atomic blocks. If there is more then one request concerning a subtask in one time only one is processed and all others just wait. When they are started they need to pass all validations. This is important, because if first request changed something in database (e.g. subtask.state) all others requests are validated and during whole validation they "see" current/new database state (after changes).

**Comment by cameel** [comment]
@pawelkisielewicz Is there anything left to do here?

**Comment by pawelkisielewicz** [comment]
@cameel  I think it is. Case when subtask exists in database is already covered. But there is still problem what happened if subtask **does not exist** in database. https://github.com/golemfactory/concent/pull/778 is good start, subtask will not be updated, but two processes creating at one time will generate DatabaseError. 
Problem from https://github.com/golemfactory/concent/issues/486 still exist, I think it will be solved in https://github.com/golemfactory/concent/issues/759. What do you think?

**Comment by pawelkisielewicz** [comment]
It is done :)
